// ---------------------------------------------------------------
// Hilfetexte zu Python: Wörter im erzeugten Code und kurze Kapitel
// Text in `Backticks` wird als Code dargestellt.
// ---------------------------------------------------------------
export interface PyDoc { title: string; text: string }
export interface PyChapter { id: string; title: string; text: string; code: string }

/** Erklärungen zu einzelnen Wörtern. Ein Klick auf das Wort im Code öffnet sie. */
export const PY_DOCS: Record<string, PyDoc> = {
  // Schlüsselwörter
  from: {title:'from … import …', text:'Holt Werkzeuge aus einem Modul ins Programm. `from pybricks.hubs import PrimeHub` heißt: Nimm aus dem Modul `pybricks.hubs` das Werkzeug `PrimeHub`. Blockwerk importiert nur, was das Programm wirklich braucht.'},
  import: {title:'from … import …', text:'Gehört zu `from`: Nach `import` stehen die Namen, die aus dem Modul geholt werden, durch Kommas getrennt.'},
  while: {title:'while – solange', text:'Wiederholt die eingerückten Zeilen darunter, solange die Bedingung wahr ist. `while True:` läuft endlos, weil `True` immer wahr ist.'},
  for: {title:'for – für jedes', text:'Wiederholt die eingerückten Zeilen für jedes Element einer Folge. `for count in range(4):` läuft viermal; `count` ist dabei nacheinander 0, 1, 2, 3.'},
  in: {title:'in', text:'Zwei Bedeutungen: In `for count in range(4)` gibt `in` an, woher die Werte kommen. In `Button.LEFT in hub.buttons.pressed()` prüft `in`, ob etwas in einer Menge enthalten ist.'},
  if: {title:'if – falls', text:'Führt die eingerückten Zeilen darunter nur aus, wenn die Bedingung wahr ist.'},
  elif: {title:'elif – sonst falls', text:'Kurz für »else if«. Wird nur geprüft, wenn die Bedingungen davor falsch waren.'},
  else: {title:'else – sonst', text:'Die eingerückten Zeilen darunter laufen, wenn die Bedingung bei `if` falsch war.'},
  not: {title:'not – nicht', text:'Dreht einen Wahrheitswert um: `not True` ist `False`.'},
  and: {title:'and – und', text:'Wahr, wenn beide Seiten wahr sind.'},
  or: {title:'or – oder', text:'Wahr, wenn mindestens eine Seite wahr ist.'},
  True: {title:'True – wahr', text:'Der Wahrheitswert »wahr«. Immer mit großem T.'},
  False: {title:'False – falsch', text:'Der Wahrheitswert »falsch«. Immer mit großem F.'},
  None: {title:'None – nichts', text:'Steht für »kein Wert«. `read_input_byte()` liefert zum Beispiel `None`, wenn nichts angekommen ist.'},
  def: {title:'def – Funktion definieren', text:'Legt eine Funktion an, also einen eigenen Befehl. Die eingerückten Zeilen darunter laufen erst, wenn die Funktion aufgerufen wird: `Ecke()`.'},
  return: {title:'return – zurückgeben', text:'Beendet eine Funktion. Steht dahinter ein Wert, bekommt ihn die Stelle, an der die Funktion aufgerufen wurde.'},
  global: {title:'global', text:'Sagt Python in einer Funktion: Diese Variable ist die aus dem Hauptprogramm, keine neue, die nur in der Funktion gilt.'},
  break: {title:'break – abbrechen', text:'Verlässt die Schleife sofort. Das Programm macht hinter der Schleife weiter.'},
  continue: {title:'continue – weiter', text:'Überspringt den Rest dieses Schleifendurchgangs und beginnt den nächsten.'},
  async: {title:'async – Funktion, die warten darf', text:'`async def` legt eine Funktion an, die an bestimmten Stellen pausieren kann, damit andere Programmteile drankommen. Blockwerk benutzt das nur, wenn mehrere Ereignisse gleichzeitig laufen.'},
  await: {title:'await – warten und die anderen dranlassen', text:'Steht vor Befehlen, die Zeit brauchen: `await wait(500)`, `await roboter.straight(200)`, auch vor dem Abfragen eines Sensors. Während dieser Programmteil wartet, laufen die anderen weiter. `await` gibt es nur in Funktionen mit `async def`.'},
  pass: {title:'pass – nichts tun', text:'Ein Platzhalter. Python verlangt nach einem Doppelpunkt mindestens eine eingerückte Zeile; ist ein Block leer, steht dort `pass`.'},
  // eingebaute Funktionen
  range: {title:'range – Zahlenfolge', text:'`range(4)` liefert die Zahlen 0, 1, 2, 3 – also vier Stück. Zusammen mit `for` ergibt das eine Schleife, die viermal läuft.'},
  print: {title:'print – ausgeben', text:'Schreibt einen Wert ins Terminal. Das beste Werkzeug, um herauszufinden, was ein Programm wirklich tut.'},
  abs: {title:'abs – Betrag', text:'Macht aus einer negativen Zahl eine positive: `abs(-5)` ist `5`.'},
  str: {title:'str – in Text umwandeln', text:'Macht aus einer Zahl einen Text: `str(42)` ist `\'42\'`. Nötig, wenn Zahlen an Texte gehängt oder auf der Lichtmatrix als Text gezeigt werden.'},
  int: {title:'int – ganze Zahl', text:'Schneidet die Nachkommastellen ab: `int(3.9)` ist `3`.'},
  float: {title:'float – Kommazahl', text:'Macht aus einer ganzen Zahl oder einem Text eine Kommazahl: `float(3)` ist `3.0`.'},
  round: {title:'round – runden', text:'Rundet auf die nächste ganze Zahl: `round(3.7)` ist `4`.'},
  ceil: {title:'ceil – aufrunden', text:'Rundet immer nach oben: `ceil(3.1)` ist `4`. Kommt aus dem Modul `umath`.'},
  floor: {title:'floor – abrunden', text:'Rundet immer nach unten: `floor(3.9)` ist `3`. Kommt aus dem Modul `umath`.'},
  len: {title:'len – Länge', text:'Liefert, wie viele Einträge eine Liste oder wie viele Zeichen ein Text hat: `len([100, 200, 300])` ist `3`.'},
  random: {title:'random – Zufall', text:'Das Modul für Zufallszahlen. Bei Pybricks heißt es eigentlich `urandom`; die Zeile `import urandom as random` gibt ihm im Programm den üblichen Namen.'},
  randint: {title:'randint – zufällige ganze Zahl', text:'`random.randint(1, 6)` liefert eine zufällige ganze Zahl von 1 bis 6, beide Grenzen eingeschlossen.'},
  as: {title:'as – unter dem Namen', text:'Gibt etwas Importiertem im Programm einen anderen Namen: `import urandom as random`.'},
  detectable_colors: {title:'detectable_colors', text:'Legt fest, welche Farben der Farbsensor überhaupt melden darf. Blockwerk nutzt das, um Schwarz in die Liste aufzunehmen.'},
  min: {title:'min – kleinster Wert', text:'Liefert den kleinsten der angegebenen Werte: `min(3, 8)` ist `3`.'},
  max: {title:'max – größter Wert', text:'Liefert den größten der angegebenen Werte: `max(3, 8)` ist `8`.'},
  // Pybricks: Klassen und Objekte
  PrimeHub: {title:'PrimeHub', text:'Die Klasse für den SPIKE-Prime-Hub. `hub = PrimeHub()` legt ein Objekt an, über das Lichtmatrix, Lautsprecher, Tasten und Gyrosensor erreichbar sind.'},
  hub: {title:'hub', text:'Das Objekt für den Hub selbst. Dahinter folgt mit Punkt, was gemeint ist: `hub.display` ist die Lichtmatrix, `hub.speaker` der Lautsprecher, `hub.light` das Statuslicht, `hub.buttons` die Tasten, `hub.imu` der Bewegungssensor.'},
  Motor: {title:'Motor', text:'Die Klasse für einen Motor. `motor_C = Motor(Port.C)` sagt: An Anschluss C steckt ein Motor, und er heißt ab jetzt `motor_C`.'},
  ColorSensor: {title:'ColorSensor', text:'Die Klasse für den Farbsensor. `farbe_C = ColorSensor(Port.C)` legt ihn an Anschluss C an.'},
  UltrasonicSensor: {title:'UltrasonicSensor', text:'Die Klasse für den Abstandssensor (Ultraschall).'},
  ForceSensor: {title:'ForceSensor', text:'Die Klasse für den Kraftsensor.'},
  DriveBase: {title:'DriveBase – Fahrbasis', text:'Fasst zwei Motoren zu einem Fahrzeug zusammen. Mit Raddurchmesser (`wheel_diameter`) und Spurbreite (`axle_track`) kann sie Strecken in mm und Drehungen in Grad fahren.'},
  roboter: {title:'roboter', text:'Der Name, den Blockwerk der Fahrbasis gibt. Alle Fahrbefehle beginnen mit `roboter.`'},
  StopWatch: {title:'StopWatch – Stoppuhr', text:'Die Klasse für eine Stoppuhr. `stoppuhr.time()` liefert die Zeit in Millisekunden, `stoppuhr.reset()` stellt sie auf 0.'},
  stoppuhr: {title:'stoppuhr', text:'Der Name, den Blockwerk der Stoppuhr gibt.'},
  Port: {title:'Port – Anschluss', text:'Die Anschlüsse am Hub: `Port.A` bis `Port.F`.'},
  Direction: {title:'Direction – Drehrichtung', text:'`Direction.COUNTERCLOCKWISE` dreht die Zählrichtung eines Motors um. Das braucht man, wenn Motoren spiegelbildlich eingebaut sind.'},
  Color: {title:'Color – Farbe', text:'Die Farben, die Pybricks kennt: `Color.RED`, `Color.GREEN`, `Color.BLUE`, `Color.YELLOW`, `Color.WHITE`, `Color.NONE` und weitere.'},
  Button: {title:'Button – Taste', text:'Die Tasten am Hub: `Button.LEFT` und `Button.RIGHT`.'},
  Icon: {title:'Icon – Bild', text:'Die eingebauten Bilder für die Lichtmatrix, zum Beispiel `Icon.HAPPY` oder `Icon.ARROW_UP`.'},
  multitask: {title:'multitask – mehreres gleichzeitig', text:'`multitask(start(), ereignis())` fasst mehrere Programmteile zusammen, die gleichzeitig laufen sollen. Genau genommen wechseln sie sich sehr schnell ab – immer an den Stellen mit `await`.'},
  run_task: {title:'run_task – Programmteile starten', text:'`run_task(...)` startet die Programmteile und läuft, bis alle fertig sind. Diese Zeile steht ganz am Ende, weil die Funktionen darüber erst angelegt sein müssen.'},
  start: {title:'start', text:'Der Name, den Blockwerk dem Programmteil unter »wenn Programm startet« gibt, sobald mehrere Ereignisse gleichzeitig laufen.'},
  ereignis: {title:'ereignis', text:'Der Name, den Blockwerk dem Programmteil unter einem Block »wenn …« gibt. Weitere heißen `ereignis2`, `ereignis3` und so weiter.'},
  nachrichten: {title:'nachrichten', text:'Ein Wörterbuch im Kopf des Programms: Zu jedem Namen einer Nachricht steht darin, wie oft sie schon gesendet wurde.'},
  sende: {title:'sende', text:'Eine kleine Funktion im Kopf des Programms. `sende(\'los\')` zählt die Nachricht »los« um eins hoch; daran erkennen die Empfänger, dass sie gesendet wurde.'},
  warte_auf: {title:'warte_auf', text:'Eine kleine Funktion im Kopf des Programms. `await warte_auf(\'los\')` wartet, bis die Nachricht »los« das nächste Mal gesendet wird.'},
  get: {title:'get – nachschlagen mit Ersatzwert', text:'`nachrichten.get(name, 0)` schlägt im Wörterbuch nach. Steht der Name noch nicht darin, kommt der Ersatzwert 0 zurück.'},
  wait: {title:'wait – warten', text:'`wait(1000)` hält das Programm 1000 Millisekunden an, also eine Sekunde.'},
  // Fernsteuerung
  XboxController: {title:'XboxController', text:'Die Klasse für einen Xbox-Controller. `controller = XboxController()` lässt den Hub nach einem Controller suchen und sich mit ihm verbinden.'},
  controller: {title:'controller', text:'Der Name, den Blockwerk dem Xbox-Controller gibt.'},
  joystick_left: {title:'joystick_left – linker Stick', text:'`controller.joystick_left()` liefert zwei Zahlen: die Stellung in x- und y-Richtung, jeweils von −100 bis 100. `[0]` wählt x, `[1]` wählt y.'},
  joystick_right: {title:'joystick_right – rechter Stick', text:'`controller.joystick_right()` liefert zwei Zahlen: die Stellung in x- und y-Richtung, jeweils von −100 bis 100. `[0]` wählt x, `[1]` wählt y.'},
  triggers: {title:'triggers – Trigger', text:'`controller.triggers()` liefert zwei Zahlen von 0 bis 100: wie weit der linke und der rechte Trigger gedrückt sind.'},
  rumble: {title:'rumble – vibrieren', text:'`controller.rumble(100, 200)` lässt den Controller mit voller Stärke 200 ms lang vibrieren.'},
  Remote: {title:'Remote – Fernbedienung', text:'Die Klasse für die LEGO-Fernbedienung (Powered Up). `fernbedienung = Remote()` lässt den Hub nach ihr suchen und sich verbinden.'},
  fernbedienung: {title:'fernbedienung', text:'Der Name, den Blockwerk der LEGO-Fernbedienung gibt.'},
  steuerung: {title:'steuerung – Steuerfeld abfragen', text:'Eine Funktion, die Blockwerk in den Kopf des Programms schreibt. `steuerung(\'x\')` liest die neuesten Eingaben aus dem Steuerfeld und gibt den gewünschten Wert zurück: `\'x\'` und `\'y\'` für den Joystick, `\'A\'` bis `\'D\'` für die Tasten.'},
  steuerfeld: {title:'steuerfeld', text:'Ein Wörterbuch (dict), in dem sich das Programm den letzten Stand von Joystick und Tasten merkt. `steuerfeld[\'x\']` ist die gespeicherte x-Stellung.'},
  steuerfeld_uhr: {title:'steuerfeld_uhr – Wächter', text:'Eine Stoppuhr, die misst, wie lange Blockwerk sich nicht mehr gemeldet hat. Nach mehr als einer Sekunde Funkstille stellt `steuerung` Joystick und Tasten auf Ruhe, damit der Roboter nicht unkontrolliert weiterfährt.'},
  read_input_byte: {title:'read_input_byte', text:'Liest ein Zeichen, das der Computer an den Hub geschickt hat, ohne darauf zu warten. Ist nichts da, kommt `None` zurück.'},
  chr: {title:'chr – Zeichen aus Zahl', text:'Macht aus einer Zahl das Zeichen mit dieser Nummer: `chr(65)` ist `\'A\'`.'},
  is: {title:'is', text:'Prüft, ob zwei Dinge dasselbe sind. Üblich ist vor allem `is None`: »Ist da kein Wert?«'},
  // Methoden
  straight: {title:'straight – geradeaus', text:'`roboter.straight(200)` fährt 200 mm geradeaus und wartet, bis der Roboter angekommen ist.'},
  turn: {title:'turn – drehen', text:'`roboter.turn(90)` dreht den Roboter auf der Stelle um 90 Grad nach rechts.'},
  arc: {title:'arc – Bogen', text:'`roboter.arc(150, 90)` fährt einen Kreisbogen mit 150 mm Radius über 90 Grad.'},
  drive: {title:'drive – losfahren', text:'`roboter.drive(200, 0)` fährt mit 200 mm/s los und wartet nicht. Die zweite Zahl ist die Drehrate in Grad pro Sekunde.'},
  stop: {title:'stop – anhalten', text:'Schaltet die Motoren ab, sie rollen aus.'},
  brake: {title:'brake – bremsen', text:'Bremst die Motoren ab.'},
  hold: {title:'hold – halten', text:'Der Motor bleibt stehen und hält seine Stellung fest.'},
  settings: {title:'settings – Einstellungen', text:'`roboter.settings(straight_speed=300, turn_rate=180)` legt Fahr- und Drehtempo fest.'},
  use_gyro: {title:'use_gyro', text:'`roboter.use_gyro(True)` lässt die Fahrbasis mit dem Gyrosensor des Hubs korrigieren. Damit fährt der Roboter gerader und dreht genauer.'},
  reset: {title:'reset – zurücksetzen', text:'Stellt Zähler auf 0: bei der Fahrbasis Strecke und Winkel, bei der Stoppuhr die Zeit.'},
  distance: {title:'distance', text:'Bei der Fahrbasis die gefahrene Strecke in mm, beim Abstandssensor die Entfernung zum Hindernis in mm.'},
  angle: {title:'angle – Winkel', text:'Bei der Fahrbasis der gedrehte Winkel des Roboters, bei einem Motor seine Drehstellung – jeweils in Grad.'},
  speed: {title:'speed – Tempo', text:'Die aktuelle Drehgeschwindigkeit eines Motors in Grad pro Sekunde.'},
  run: {title:'run – laufen', text:'`motor_C.run(500)` schaltet den Motor ein. Er läuft, bis er angehalten wird.'},
  run_angle: {title:'run_angle', text:'`motor_C.run_angle(500, 360)` dreht den Motor mit Tempo 500 um 360 Grad weiter. Erst das Tempo, dann der Winkel.'},
  run_time: {title:'run_time', text:'`motor_C.run_time(500, 1000)` lässt den Motor mit Tempo 500 genau 1000 ms laufen.'},
  run_target: {title:'run_target', text:'`motor_C.run_target(500, 90)` dreht den Motor auf die Stellung 90 Grad.'},
  reset_angle: {title:'reset_angle', text:'`motor_C.reset_angle(0)` erklärt die jetzige Stellung des Motors zu 0 Grad.'},
  color: {title:'color – Farbe messen', text:'`farbe_C.color()` liefert die Farbe, die der Sensor sieht, zum Beispiel `Color.RED`.'},
  reflection: {title:'reflection – Reflexion', text:'`farbe_C.reflection()` liefert die Helligkeit des Untergrunds von 0 (dunkel) bis 100 (hell).'},
  pressed: {title:'pressed – gedrückt', text:'Beim Kraftsensor `True` oder `False`. Bei `hub.buttons.pressed()` die Menge aller gerade gedrückten Tasten.'},
  force: {title:'force – Kraft', text:'`kraft_E.force()` liefert die Druckkraft in Newton.'},
  heading: {title:'heading – Ausrichtung', text:'`hub.imu.heading()` liefert, wie weit sich der Hub seit dem Start gedreht hat, in Grad.'},
  reset_heading: {title:'reset_heading', text:'`hub.imu.reset_heading(0)` erklärt die jetzige Richtung zu 0 Grad.'},
  time: {title:'time – Zeit', text:'`stoppuhr.time()` liefert die Zeit in Millisekunden.'},
  display: {title:'display – Lichtmatrix', text:'Die 5×5-Lichtmatrix des Hubs. `hub.display.text(…)`, `.number(…)`, `.icon(…)` und `.off()`.'},
  speaker: {title:'speaker – Lautsprecher', text:'`hub.speaker.beep(440, 200)` spielt einen Ton mit 440 Hz für 200 ms.'},
  beep: {title:'beep – Piepton', text:'`hub.speaker.beep(440, 200)`: zuerst die Tonhöhe in Hz, dann die Dauer in ms.'},
  light: {title:'light – Statuslicht', text:'Das Licht an der mittleren Taste. `hub.light.on(Color.GREEN)` schaltet es ein, `hub.light.off()` aus.'},
  imu: {title:'imu – Bewegungssensor', text:'Der eingebaute Sensor für Drehung und Neigung. Die Abkürzung steht für »inertial measurement unit«.'},
  buttons: {title:'buttons – Tasten', text:'Die Tasten des Hubs. `hub.buttons.pressed()` liefert alle, die gerade gedrückt sind.'}
};

/** Kurze Kapitel für den Umstieg von Blöcken auf Python. */
export const PY_CHAPTERS: PyChapter[] = [
  {id:'aufbau', title:'Wie ein Pybricks-Programm aufgebaut ist',
   text:'Jedes Programm hat zwei Teile. Im Kopf stehen die Importe und die Geräte: Welcher Hub ist es, was steckt an welchem Anschluss? Darunter folgt das eigentliche Programm, das von oben nach unten abgearbeitet wird.\n\nZeilen, die mit `#` beginnen, sind Kommentare. Python überspringt sie; sie sind Notizen für Menschen.',
   code:'from pybricks.hubs import PrimeHub\nfrom pybricks.parameters import Port\nfrom pybricks.pupdevices import Motor\nfrom pybricks.tools import wait\n\nhub = PrimeHub()\n\n# Geräte an den Anschlüssen\nmotor_C = Motor(Port.C)\n\n# Ab hier das eigentliche Programm\nmotor_C.run_angle(500, 360)\nwait(1000)\n'},
  {id:'einrueckung', title:'Einrückung',
   text:'In der Block-Sprache umschließt ein Block wie »wiederhole« die Blöcke in seinem Inneren. Python zeigt dasselbe durch Einrückung: Nach einem Doppelpunkt gehören alle Zeilen dazu, die vier Leerzeichen weiter rechts stehen. Sobald eine Zeile wieder weiter links beginnt, ist der innere Teil vorbei.\n\nDie Einrückung ist also keine Verzierung – sie ändert, was das Programm tut.',
   code:'from pybricks.tools import wait\n\nfor count in range(3):\n    print(\'in der Schleife\')\n    wait(500)\nprint(\'nach der Schleife\')\n'},
  {id:'variablen', title:'Variablen',
   text:'Eine Variable ist ein Name für einen Wert. Mit `=` bekommt sie einen Wert zugewiesen: Rechts wird gerechnet, das Ergebnis landet links.\n\n`Zaehler = Zaehler + 1` ist deshalb keine falsche Gleichung, sondern heißt: Nimm den alten Wert, zähle 1 dazu, speichere das Ergebnis wieder unter demselben Namen.\n\nNamen dürfen Buchstaben, Ziffern und den Unterstrich enthalten, aber keine Leerzeichen und keine Umlaute.',
   code:'Zaehler = 0\nZaehler = Zaehler + 1\nZaehler = Zaehler + 1\nprint(Zaehler)\n'},
  {id:'schleifen', title:'Schleifen',
   text:'`for count in range(4):` wiederholt eine feste Anzahl von Malen. `while Bedingung:` wiederholt, solange die Bedingung wahr ist. `while True:` hört nie von selbst auf.\n\nMit `break` lässt sich jede Schleife vorzeitig verlassen.',
   code:'from pybricks.tools import wait\n\nfor count in range(4):\n    print(count)\n\nSekunden = 3\nwhile Sekunden > 0:\n    print(Sekunden)\n    wait(1000)\n    Sekunden = Sekunden - 1\n'},
  {id:'bedingungen', title:'Bedingungen',
   text:'`if` prüft eine Bedingung und führt die eingerückten Zeilen nur aus, wenn sie wahr ist. `else` ist der Zweig für »sonst«, `elif` prüft eine weitere Bedingung.\n\nVerglichen wird mit `==` (gleich), `!=` (ungleich), `<`, `>`, `<=`, `>=`. Mit `and`, `or` und `not` lassen sich Bedingungen verknüpfen.\n\nHäufiger Fehler: `=` weist zu, `==` vergleicht.',
   code:'Abstand = 80\n\nif Abstand < 100:\n    print(\'nah\')\nelif Abstand < 500:\n    print(\'mittel\')\nelse:\n    print(\'weit weg\')\n'},
  {id:'funktionen', title:'Funktionen',
   text:'Eine Funktion ist ein eigener Befehl – das, was in Blockwerk »Meine Blöcke« heißt. `def` legt sie an, aufgerufen wird sie mit ihrem Namen und Klammern.\n\nIn den Klammern können Eingaben stehen (Parameter). Mit `return` gibt eine Funktion ein Ergebnis zurück.\n\nFunktionen müssen im Programm über der Stelle stehen, an der sie benutzt werden.',
   code:'def Verdopple(x):\n    return x * 2\n\ndef Sage_hallo():\n    print(\'Hallo\')\n\nSage_hallo()\nprint(Verdopple(21))\n'},
  {id:'gleichzeitig', title:'Mehreres gleichzeitig',
   text:'Mit einem einzigen Ereignis läuft das Programm Zeile für Zeile von oben nach unten. Sollen mehrere Ereignisse gleichzeitig laufen, baut Blockwerk das Programm um: Jedes Ereignis wird eine Funktion mit `async def`, und die letzte Zeile startet alle zusammen.\n\nDer Hub kann in Wahrheit nur eine Sache auf einmal. Die Programmteile wechseln sich ab – an jeder Stelle mit `await`. Deshalb steht `await` vor allem, was Zeit braucht. Eine Schleife ohne `await` würde die anderen aussperren; Blockwerk setzt dort `await wait(0)` ein.',
   code:'from pybricks.hubs import PrimeHub\nfrom pybricks.parameters import Button\nfrom pybricks.tools import wait, multitask, run_task\n\nhub = PrimeHub()\n\nasync def start():\n    while True:\n        await hub.speaker.beep(440, 100)\n        await wait(1000)\n\nasync def ereignis():\n    while True:\n        while not (Button.LEFT in hub.buttons.pressed()):\n            await wait(10)\n        hub.display.number(1)\n        while Button.LEFT in hub.buttons.pressed():\n            await wait(10)\n\n# Alle Programmteile gleichzeitig starten\nrun_task(multitask(start(), ereignis()))\n'},
  {id:'objekte', title:'Punkt und Klammern',
   text:'In `roboter.straight(200)` stecken drei Teile: `roboter` ist das Ding, um das es geht (ein Objekt). Nach dem Punkt steht, was es tun soll (eine Methode). In den Klammern stehen die Angaben dazu.\n\nKlammern ohne Inhalt bedeuten: Tu es, es sind keine Angaben nötig – zum Beispiel `roboter.distance()`. Lässt man die Klammern weg, passiert nichts.\n\nSo ist auch `hub.display.icon(Icon.HAPPY)` zu lesen: vom Hub die Lichtmatrix, und die zeigt ein Bild.',
   code:'from pybricks.hubs import PrimeHub\nfrom pybricks.parameters import Icon\nfrom pybricks.tools import wait\n\nhub = PrimeHub()\n\nhub.display.icon(Icon.HAPPY)\nwait(2000)\nhub.display.off()\n'},
  {id:'fehler', title:'Fehlermeldungen lesen',
   text:'Geht etwas schief, schreibt der Hub eine Fehlermeldung ins Terminal. Wichtig sind zwei Dinge: die Zeilennummer (`line 12`) und die letzte Zeile mit der Art des Fehlers.\n\n`OSError: [Errno 19] ENODEV` heißt: Am Anschluss steckt nicht das erwartete Gerät. `NameError` heißt: Ein Name ist unbekannt, oft ein Tippfehler. `SyntaxError` heißt: Python versteht die Zeile nicht, oft fehlt ein Doppelpunkt oder eine Klammer. `ZeroDivisionError` heißt: Es wurde durch 0 geteilt.\n\nBlockwerk markiert bei einem Fehler den Block, aus dem die Zeile stammt.',
   code:'Strecke = 100\nZeit = 0\n\nif Zeit != 0:\n    print(Strecke / Zeit)\nelse:\n    print(\'Zeit ist 0 - teilen geht nicht\')\n'}
];
